### PR TITLE
Add vercel support & some other small updates

### PR DESCRIPTION
**Pull request by mrsproutt**
Pretty self explanatory

### CODE REVIEW

**Comment by proudparrot2** [comment]
I don’t want the package-lock.json file included - is there a reason its there?

**Comment by proudparrot2** [comment]
Other than that it looks fine. How would vercel support be added by default?

**Comment by Russell2259** [comment]
The vercel.json file

**Comment by mdoryammilwalrus** [comment]
> I don’t want the package-lock.json file included - is there a reason its there?

The package-lock should be there, it helps speed up `npm install`s because NPM does not have to resolve all the packages every time

**Comment by mdoryammilwalrus** [comment]
> Do we want the package-lock.json or not?

yes

**Pull request merged**
