### PR TITLE
It hurt my eyes looking at the input field so i added css to it

### PR DESCRIPTION
**Pull request by HallowedSpace**
👍

### CODE REVIEW

**Comment by Asleep123** [comment]
Hey there. It appears there's a error in your code. In the style element, you put `#url-input`, when the ID the textbox uses is `urlInput`. Please fix this error in your code.

**Comment by proudparrot2** [comment]
could you also send a screenshot of what it looks like because I can’t preview it rn

**Comment by Asleep123** [comment]
it just makes it more rounded and bigger, there’s a error in the code tho

**Comment by HallowedSpace** [comment]
@proudparrot2 here is a preview. I will fix the error in the code but here is a preview of it
image

**Comment by HallowedSpace** [comment]
@proudparrot2 this is a preview
image

**Comment by HallowedSpace** [comment]
despite the fact that it is only changing the border radius property

**Comment by HallowedSpace** [comment]
also sorry for being late i had some things happening in real life i had to do

**Pull request closed without merging**
